### ISSUE TITLE
find out why the fuck menuOption styles are not included in the compiled css

### ISSUE THREAD

**Issue by VictrumMaximum** [VictrumMaximum/outofskin#20]
for now, the style is added as inline in the render method

**Comment by VictrumMaximum** [comment]
turns out this is a problem for all styles in the menu...

**Comment by l33t0r** [comment]
I believe @VictrumMaximum is part of the problem here.

**Comment by VictrumMaximum** [comment]
fixed while refactoring webpack config and fixing the paths for static files in express
